### ISSUE TITLE
Transactions are mined 10-20 blocks after being sent to the network

### ISSUE THREAD

**Issue by raduciobanu22** [kadena-io/devnet#8]
I am running devnet with the default configuration from `main` branch and experiencing this delay of anywhere from 10 to 20 (or sometimes more) blocks that get mined before the transaction that I sent to the network gets mined. This translates into 4-6 minutes of waiting time with the default 30s block time.
I've got this issue on 2 different hardware configurations, one with 4 CPUs and another with 6 CPUs, 16GB RAM, SSD, both Ubuntu and MacOS

**Comment by ggobugi27** [comment]
If the transactions are taking too long, I suggest trying the minimal devnet setting.  https://github.com/kadena-io/devnet#minimal-devnet

**Comment by raduciobanu22** [comment]
@ggobugi27 The minimal setup does work as expected. Would be curious to know why the regular 2-3 nodes setup doesn't though.
